version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice_python
    env_file:
      - .env
    volumes:
      - ${PWD}../scripts:/home/root
    stdin_open: true
    tty: true
