version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice_python
    env_file:
      - .env
    volumes:
      - ${PWD}../scripts:/home/root
    stdin_open: true
    tty: true

  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    environment:
      - SERVICES=s3
    ports:
      - 4566:4566
      - 4571:4571
